version: '2.1'
services:
  app:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'docker.local'
    ports:
     - "8080:80"
     - "8443:443"
     - "2222:22"
    volumes:
     - ./config:/etc/gitlab
     - ./logs:/var/log/gitlab
     - ./data:/var/opt/gitlab
#     - ./ssl:/etc/gitlab/ssl
