web:
  container_name: gl-stewart
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'localhost:8080'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:8080'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8080:80'
    - '8443:443'
    - '8022:22'
  volumes:
    - ./gitlab/config:/etc/gitlab
    - ./logs:/var/log/gitlab
    - ./gitlab/data:/var/opt/gitlab
#    - ./gitlab/ssl:/etc/nginx/ssl
